const giftsList = [
    {
        id: 1,
        name: "Granola siêu hạt ăn kiêng 15% yến mạch",
        imageSrc: "/image-01.png",
        rating: 4,
        price: 133000,
        discount: "-99%",
        status: 1,
        type: "",
        category: "Danh mục 3",
        description: "",
        addDate: "2024-11-08"
    },
    {
        id: 2,
        name: "Hạnh nhân rang muối biển, 240g",
        imageSrc: "/image-02.png",
        rating: 4,
        price: 155000,
        discount: "-99%",
        status: 1,
        type: "hũ",
        category: "Danh mục 3",
        description: "",
        addDate: "2024-11-08"
    },
    {
        id: 3,
        name: "Ngũ hạt thập cẩm, 135g",
        imageSrc: "/image-03.png",
        rating: 4,
        price: 42000,
        discount: "-99%",
        status: 1,
        type: "hũ",
        category: "Danh mục 1",
        description: "",
        addDate: "2024-11-08"
    },
    {
        id: 4,
        name: "Đậu hoà lan wasabi, 150g",
        imageSrc: "/image-04.png",
        rating: 4,
        price: 42000,
        discount: "-99%",
        status: 1,
        type: "hũ",
        category: "Danh mục 2",
        description: "",
        addDate: "2024-11-08"
    },
    {
        id: 5,
        name: "Nước cốt dâu tằm, 300ml",
        imageSrc: "/image-05.png",
        rating: 4,
        price: 54000,
        discount: "-99%",
        status: 1,
        type: "chai",
        category: "Danh mục 1",
        description: "",
        addDate: "2024-11-08"
    },
    {
        id: 6,
        name: "Trà sencha hoa hồng, 86g",
        imageSrc: "/image-06.png",
        rating: 4,
        price: 109000,
        discount: "-99%",
        status: 1,
        type: "hộp",
        category: "Danh mục 2",
        description: "",
        addDate: "2024-11-08"
    },
    {
        id: 7,
        name: "Bột trà xanh matcha túi 4g",
        imageSrc: "/image-07.png",
        rating: 4,
        price: 36000,
        discount: "-99%",
        status: 1,
        type: "",
        category: "Danh mục 3",
        description: "",
        addDate: "2024-11-22"
    },
    {
        id: 8,
        name: "Bột rau má, 100g, bịch",
        imageSrc: "/image-08.png",
        rating: 4,
        price: 100000,
        discount: "-99%",
        status: 1,
        type: "bịch",
        category: "Danh mục 1",
        description: "",
        addDate: "2024-11-08"
    },
    {
        id: 9,
        name: "Ngũ hạt thập cẩm, 135g",
        imageSrc: "/image-03.png",
        rating: 4,
        price: 42000,
        discount: "-99%",
        status: 1,
        type: "hũ",
        category: "Danh mục 1",
        description: "",
        addDate: "2024-11-01"
    },
    {
        id: 10,
        name: "Đậu hoà lan wasabi, 150g",
        imageSrc: "/image-04.png",
        rating: 4,
        price: 42000,
        discount: "-99%",
        status: 1,
        type: "hũ",
        category: "Danh mục 1",
        description: "",
        addDate: "2024-11-01"
    }
];

export default giftsList